sudo: required
dist: focal
stages:
- name: Deploy
jobs:
  include:
  - stage: Deploy
    name: Deploy bot to server
    language: python
    python: '3.8'
    cache: pip
    before_install:
    - openssl aes-256-cbc -K $encrypted_b06a1a195e3f_key -iv $encrypted_b06a1a195e3f_iv
      -in ansible.enc -out ./ansible -d
    - chmod 600 ansible
    - openssl aes-256-cbc -K $encrypted_5a553d836f7c_key -iv $encrypted_5a553d836f7c_iv
      -in deploymentFiles/docker-compose.yml.enc -out ./playbooks/docker-compose.yml -d
    - openssl aes-256-cbc -K $encrypted_d64d9031a8dc_key -iv $encrypted_d64d9031a8dc_iv
      -in deploymentFiles/ansible_hosts.enc -out ./ansible_hosts -d
    install:
    - pip install ansible
    script:
    - ansible-playbook playbooks/deploy.yml

