version: '3.4'

services:
  animenotifierbot:
    image: animenotifierbot
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./database:/bot/database
    environment:
      - TOKEN=<TOKEN>
      - PREFIX=*
    restart: always